version: '3.8'

networks:
  laravel:

services:
  webserver:
    image: 'nginx:latest'
    container_name: ${PROJECT_NAME}-nginx
    restart: always
    working_dir: /var/www
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # - ./nginx/.htaccess:/app/public/.htaccess
      - ./:/var/www/public
      #- ./html:/usr/share/nginx/html
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - backend
      # - db
    networks:
      laravel:

  backend:
    image: 'php:7.4-fpm'
    # build:
    #   context: "./docker/php"
    #   dockerfile: Dockerfile
    container_name: ${PROJECT_NAME}-backend
    networks:
      - laravel
    ports:
      - '9000:9000'
    # depends_on:
    #   - db
    volumes:
      - ./:/var/www/public

  # php-cli:
  #   image: "php:7.4-cli"
  #   container_name: ${PROJECT_NAME}-php-cli
  #   working_dir: /var/www
  #   volumes:
  #     - ./:/var/www/public

  # db:
  #   container_name: ${PROJECT_NAME}-db
  #   image: mysql
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
  #     MYSQL_DATABASE: MYSQL_DATABASE
  #     MYSQL_USER: MYSQL_USER
  #     MYSQL_PASSWORD: MYSQL_PASSWORD
  #   ports:
  #     - "9906:3306"
  #   networks:
  #     - laravel

  # phpmyadmin:
  #   container_name: ${PROJECT_NAME}-phpmyadmin
  #   image: phpmyadmin/phpmyadmin
  #   ports:
  #     - "8088:80"
  #   restart: always
  #   environment:
  #     - PMA_HOST=db
  #   depends_on:
  #     - db
